Roulette.xcodeproj/project.pbxproj, Roulette/Model/Member.swift, Roulette/Model/TransactionRecord.swift, Roulette/Model/UserDefaultsRepository.swift, Roulette/Model/WarikanGroup.swift
UserDefaultsRepositroyを追加しました。
=> add: UserDefaultsRepositroy

Roulette/Views/TatekaeDetailView.swift, Roulette/Views/TatekaeListView.swift
=> Change: TatekaeDetailViewを再定義

Roulette.xcodeproj/project.pbxproj, Roulette/ViewRouter.swift, Roulette/Views/ConfirmView.swift, Roulette/Views/GroupListView.swift, Roulette/Views/TatekaeListView.swift
ConfiremVIewの追加
NaivgtaionStackが複数あることで起こっていた問題を修正
=> add: ConfiremViewを追加

Roulette/Views/ArchiveView.swift, Roulette/Views/ConfirmView.swift, Roulette/Views/RouletteResultView.swift, Roulette/Views/TatekaeDetailView.swift
モーダル表示の際にタイトルをキャンセルボタンが付与されるようにした。清算済割り勘グループを表示するArchiveViewを作成した。
=> Change: TatekaeDetailView, ConfirmView, ArchiveViewを変更

Roulette/Views/GroupListView.swift, Roulette/Views/TatekaeListView.swift
モーダルで表示される親のViewにて"interactiveDismissDisabled"を適用
=> change: モーダルをスワイプで閉じれないよう変更

Roulette/Views/AddGroupView.swift, Roulette/Views/AddTatekaeView.swift
=> change: メンバーの追加箇所を変更＆軽微な変更

Roulette.xcodeproj/project.pbxproj, Roulette/Views/ArchiveView.swift, Roulette/Views/ArchivedSeisanResultView.swift
アーカイブ表示用の"SeisanResultView"として"ArchivedSeisanResultView"を作成した。
=> Add: ArchivedSeisanResultViewを追加

Roulette/Model/UseCase/WarikanGroupUseCase.swift
=> Feature: 指定したIDの割り勘グループの立て替えリストを返すユースケースを追加

Roulette/ViewModels/GroupListViewModel.swift, Roulette/Views/AddGroupView.swift, Roulette/Views/GroupListView.swift
バリデーションの記述
GroupListViewへ値を渡すためのクロージャ処理を記述
=> Change: AddGroupViewの内部処理を記述

Roulette/ViewModels/TatekaeListViewModel.swift, Roulette/Views/AddGroupView.swift, Roulette/Views/GroupListView.swift, Roulette/Views/TatekaeListView.swift, Roulette/Views/ViewRouter.swift
TatekaeListViewModelに内部処理を記述した。これに伴う変更をGroupListView, TatekaeListViewに対して行った。
=> Change: TatekaeListViewとTatekaeListViewModelの変更

Roulette/Model/Repository/Member/Member.swift, Roulette/Model/Repository/WarikanGroup/WarikanGroup.swift, Roulette/Views/GroupListView.swift, Roulette/Views/TatekaeListView.swift, Roulette/Views/ViewRouter.swift
GroupLitView, TatekaeListViewが依存関係を持たぬよう変更した。それに伴い、ViewRouter, WarikanGroup, Memberを修正した。
=> Change: GroupListView, TatekaeListView, ViewRouter, WarikanGroup, Memberを変更

Roulette/Views/TatekaeListView.swift
TatekaeListViewにMainViewModelを付与し、ダミーデータをViewModelのプロパティに置き換えた。
=> Feature: TatekaeListViewにMainViewModelを付与

Roulette/Views/AddTatekaeView.swift
MemberのHashable適合は必須ではなかったため、プルリクエストを再度プルリクエストを作成した。
=> Change: AddTatekaeViewにMainViewModelを付与

Roulette/Views/TatekaeListView.swift
TatekaeDetailViewを表示させる処理が未記入だったため、記入した。
=> Feature: TatekaeDetailViewを表示させる処理を記入

Roulette/Views/GroupListView.swift
- fix: AddButtonの処理が空だったので処理を追加
- fix: 不自然な命名を修正
=> Fix: GroupListViewのAddButtonと不自然な命名を修正

Roulette/ViewModels/MainViewModel.swift, Roulette/Views/GroupListView.swift, Roulette/Views/TatekaeListView.swift
・MainViewModelにselectWarikanGroupメソッドを追加
・GroupListViewのNavigtaionLinkをButtonに変更
・navigationTitleでタイトルが表示されるよう変更
=> Change：GroupListViewのタイトルが表示されるよう変更

Roulette/ViewModels/MainViewModel.swift, Roulette/Views/RouletteView.swift
・MainViewModelを付与
・MainViewModelからメンバーを取得
・ルーレットを回した後に、NavigationLinkのボタンを表示させる
・ランダムでメンバーを選ぶメソッドを追加
=> Change: RouletteViewでグループのメンバーを取得して、ルーレットを回すよう変更

Roulette/Views/RouletteResultView.swift
・mainViewModelを付与
・アンラッキーメンバーを保持するためのunluckyMenber（@State）プロパティを付与
・taskを使いメンバーをgetMember(id:)から取得
=> change: 選ばれたアンラッキーメンバーを表示させるよう変更

Roulette.xcodeproj/project.pbxproj, Roulette/Model/Repository/ArchivedWarikanGroup/ArchivedWarikanGroupRepository.swift, Roulette/Model/Repository/ArchivedWarikanGroup/InMemoryArchivedWarikanGroupRepository.swift
作り忘れていたArchivedWarikanGroupのリポジトリの実装を追加しました。
マージはレビュワーに任せます。
作業用に切っているブランチがあれば、そこにもマージしてください。
=> Feature: ArchivedWarikanGroupのリポジトリを作成した

Roulette/ViewModels/ArchiveViewModel.swift, Roulette/Views/ArchiveView.swift
・@PubishedでarchivedWarikanGroupsDataListを付与
=> Change：ArchiveViewModelの初期化処理を記述。

Roulette.xcodeproj/project.pbxproj, Roulette/ViewModels/ArchiveViewModel.swift, Roulette/ViewModels/ArchivedSeisanResultViewModel.swift, Roulette/Views/ArchiveView.swift, Roulette/Views/ArchivedSeisanResultView.swift
- refactor: 変数名、関数名の修正及び不要なスペースの削除
- change: ArchiveViewにViewModel内のデータをリスト表示させるよう変更
- add: ArchivedSeisanResultViewModelの作成
- change: ArchivedSeisanResultViewのダミーデータをViewModelのデータに置き換え
- change: ArchivedSeisanResultViewにて@StateObject用のイニシャライザを作成
- change: ダミーのTextインスタンスをArchivedSeisanResultViewへのNavigationLinkに変更
- fix: 条件式の修正
- fix: ArchivedSeisanResultView.viewDataに対して@Publishedを付与
=> Feature: ArchivedSeisanResultViewModelの実装

Roulette/ViewModels/MainViewModel.swift, Roulette/Views/RouletteResultView.swift, Roulette/Views/RouletteView.swift, Roulette/Views/SeisanResultView.swift
・unluckyMemberの型をStringへ変更
・変更に伴っては発生するエラーを修正
=> change: MainViewModelが持つunluckyMemberの変更に伴って発生するエラーを修正

Roulette/Model/Repository/Tatekae/TatekaeRepository.swift
=> Refactor: TatekaeRepositoryのuserdefaltsKeyをletに変更

Roulette/ViewModels/MainViewModel.swift, Roulette/Views/RouletteResultView.swift, Roulette/Views/RouletteView.swift, Roulette/Views/SeisanResultView.swift
MainViewModelがもつunluckyMemberをunluckyMemberNameに変更
=> Rename: MainViewModel内のプロパティの変更

Roulette/ViewModels/MainViewModel.swift, Roulette/Views/RouletteView.swift
・convertSeisanResponseToSuccessメソッドを追加
=> Change: MainViewModelにResponseのプロパティを書き換えるメソッドを追加

Roulette/Views/RouletteView.swift
- remove: 不要なコメントを削除
- chore: 許容範囲外のケースに対して出力（print）を追加
=> Refactor: RouletteViewの不要なコメントの削除・許容範囲外のケースに対しての出力追加

Roulette/Model/UseCase/DTO/ArchivedWarikanGroupData.swift, Roulette/Views/ArchiveView.swift
=> Rename: ArchivedWarikanGroupDataのnameをgroupNameに改名

Roulette/Util/Extensions.swift, Roulette/Views/TatekaeListView.swift
- feat: Date型に計算型プロパティstringを付与
- change: TatekaeListViewの立替日時のダミーデータを実際のデータに変更
=> Change: TatekaeListViewの立替日時のダミーデータを実際のデータに変更

Roulette/ViewModels/AddGroupViewModel.swift, Roulette/ViewModels/MainViewModel.swift, Roulette/Views/AddGroupView.swift, Roulette/Views/GroupListView.swift
- feat: AddGroupViewModelを作成
- change: AddGroupViewがもつViewModelをMainViewModelからAddGroupViewModelに変更
=> Feature: AddGroupViewのViewModelをMainViewModelからAddGroupViewModelに変更

Roulette/Views/GroupListView.swift, Roulette/Views/TatekaeListView.swift, Roulette/Views/ViewRouter.swift
- change: TatekaeListViewのViewModelを変更
- TatekaeListViewのnavigationTitleの動的実装
- change: TatekaeListViewのUIロジックの変更
=> Change: TatekaeListViewのViewModelを変更

Roulette/Util/Extensions.swift
=> Chore: 不要となったDate型のextentionを削除

Roulette/ViewModels/TatekaeListViewModel/TatekaeListViewModel.swift, Roulette/Views/TatekaeListView.swift
=> Feature: 立替の削除機能を実装

Roulette/Model/Repository/ArchivedWarikanGroup/InMemoryArchivedWarikanGroupRepository.swift, Roulette/Model/Repository/Member/InMemoryMemberRepository.swift, Roulette/Model/Repository/Tatekae/InMemoryTatekaeRepository.swift, Roulette/Model/Repository/WarikanGroup/InMemoryWarikanGroupRepository.swift, Roulette/Model/UseCase/SeisanCalculator/SeisanCalculator.swift, RouletteTests/SeisanCalculatorTests.swift
=> Test: UnitTestを更新

Roulette/Model/Repository/Tatekae/TatekaeRepository.swift
=> Refactor: TatekaeRepositoryをstructに変更

Roulette.xcodeproj/project.pbxproj, Roulette/ViewModels/ConfirmViewModel.swift, Roulette/ViewModels/ConfirmViewModel/ConfirmViewModel.swift, Roulette/ViewModels/ConfirmViewModel/ConfirmViewModelDTO.swift, Roulette/Views/ConfirmView.swift, Roulette/Views/GroupListView.swift, Roulette/Views/TatekaeListView.swift, Roulette/Views/ViewRouter.swift
- feature: ConfirmViewModelを作成
- change: ConfirmViewのMainViewModelをConfirmViewModelに変更
=> Feature: ConfirmViewModelの実装

Roulette/Views/ConfirmView.swift
- **fix: 立て替えの数が多いとConfirmViewがバグる問題を修正（#202)**
close #202
=> Fix: 立て替えの数が多いとConfirmViewがバグる問題を修正（#202)

Roulette/Views/AddGroupView.swift, Roulette/Views/AddTatekaeView.swift, Roulette/Views/ConfirmView.swift, Roulette/Views/RouletteResultView.swift
- **change: グループを作成するボタンのコード変更**
- **change: 立替を作成するボタンのコード変更**
- **change: RouletteViewに遷移するボタンのコード変更**
- **change: SeisanResultViewに遷移するボタンのコード変更**
close #203
=> Change: ボタンのタップ領域の見直し

Roulette/ViewModels/AddGroupViewModel/AddGroupViewModel.swift, Roulette/ViewModels/AddTatekaeViewModel/AddTatekaeViewModel.swift, Roulette/Views/AddGroupView.swift, Roulette/Views/AddTatekaeView.swift, Roulette/Views/GroupListView.swift
- **change: AddGroupViewのinteractiveDismissDisabledを変更**
- **change: AddTatekaeViewのinteractiveDismissDisabledを変更**
=> Enhancement: 入力が何もない場合はモーダルをスワイプで閉じれるように変更
